use bbdtvm  

CREATE SCHEMA bus3

CREATE TABLE bus3.RISCO(
	ID_RISCO INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	NM_RISCO VARCHAR(50) UNIQUE NOT NULL,
	DESCRICAO VARCHAR(150)
)
GO

INSERT INTO bus3.RISCO (NM_RISCO) 
VALUES ('Baixo'),
		('Médio'),
		('Alto')  
GO



CREATE TABLE bus3.FUNDO(
	COD_FUNDO INT NOT NULL PRIMARY KEY,
	CNPJ_FUNDO VARCHAR(14) ,
	NM_FUNDO VARCHAR(150),
	DT_ABERTURA DATE,
	DT_ENCERRAMENTO DATE,
	ID_RISCO INT NOT NULL,
	FOREIGN KEY (ID_RISCO) REFERENCES bus3.RISCO(ID_RISCO),
	INDEX IX_NM_FDO(NM_FUNDO),
	INDEX IX_RSC_FDO(CNPJ_FUNDO)
)
GO



CREATE TABLE bus3.PERFIL (
	ID_PERFIL INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	NM_PERFIL VARCHAR(50),
	DESCRICAO VARCHAR (150)
)
GO

INSERT INTO bus3.PERFIL (NM_PERFIL , DESCRICAO) 
VALUES ('Conservador' , 'Não quer correr nenhum ou poucos riscos' ),
		('Moderado' , 'Aceita correr um certo risco nas aplicações'),
		('Arrojado' , 'Aceita correr mais riscos para ter mais rentabilidade')  
GO

CREATE TABLE bus3.PERFIL_RISCO(
	ID_PERFIL INT,
	ID_RISCO INT,
	PRIMARY KEY (ID_PERFIL , ID_RISCO),
	FOREIGN KEY (ID_PERFIL)REFERENCES bus3.PERFIL(ID_PERFIL),
	FOREIGN KEY (ID_RISCO) REFERENCES bus3.RISCO(ID_RISCO)
)
GO

INSERT INTO bus3.PERFIL_RISCO (ID_PERFIL , ID_RISCO) 
VALUES (1 , 1 ),
	(2 , 1 ),
 	(2 , 2 ),
 	(3 , 1 ),
 	(3 , 2 ),
 	(3 , 3 )
GO

CREATE TABLE bus3.COTAS (
	DT_COTA DATE,
	COD_FUNDO INT,
	COTA DOUBLE PRECISION,
	PRIMARY KEY (DT_COTA , COD_FUNDO),
	FOREIGN KEY (COD_FUNDO) REFERENCES bus3.FUNDO(COD_FUNDO) 
)
GO

CREATE TABLE bus3.CONF(
	NUM_MAX_FUND INT
)
GO

INSERT INTO bus3.CONF (NUM_MAX_FUND) VALUES (3)
GO


CREATE VIEW RENTABILIDADE AS 
(
SELECT top(1)
	c.DT_COTA , 
	c.COD_FUNDO , 
	(C.COTA / LEAD(c.COTA , 22 , 0) OVER(ORDER by COD_FUNDO ,DT_COTA DESC) -1)  D30,
	(C.COTA / LEAD(c.COTA , 64 , 0) OVER(ORDER by COD_FUNDO ,DT_COTA DESC) -1)  D90,
	(C.COTA / LEAD(c.COTA , 128 , 0) OVER(ORDER by COD_FUNDO ,DT_COTA DESC) -1)  D180,
	(C.COTA / LEAD(c.COTA , 256 , 0) OVER(ORDER by COD_FUNDO ,DT_COTA DESC) -1)  D360
from bus3.COTAS c 
)

